# Generated by Django 3.2.3 on 2021-05-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210525_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='product_id',
            field=models.IntegerField(max_length=10),
        ),
    ]
