# Generated by Django 3.2.3 on 2021-05-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_like_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
