# Generated by Django 3.2.3 on 2021-05-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_like_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='product_id',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
