# Generated by Django 3.2.3 on 2021-06-19 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20210619_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
