# Generated by Django 3.2.3 on 2021-05-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20210525_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='product_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='like',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
