# Generated by Django 3.2.3 on 2021-05-26 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_like_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='user_id',
            new_name='user',
        ),
    ]
